server:
  port : 8088

spring:
  datasource:
    url: jdbc:h2:mem:java-web-demo
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: INFO
  file:
    name: /tmp/app.log
